# Generated by Django 5.0.6 on 2024-07-11 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
