# Generated by Django 5.0.6 on 2024-07-04 14:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=60)),
                ('cities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=None)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('hotels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=None)),
                ('flight_out_number', models.CharField(max_length=10)),
                ('flight_out_time', models.DateTimeField()),
                ('flight_back_number', models.CharField(max_length=10)),
                ('flight_back_time', models.DateTimeField()),
                ('activities', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('itinerary', models.TextField()),
                ('budget', models.FloatField()),
                ('hotels_cost', models.FloatField()),
                ('flights_cost', models.FloatField()),
            ],
        ),
    ]
