# Generated by Django 5.0.6 on 2024-07-10 09:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_remove_trip_costs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), size=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=500), size=None),
        ),
    ]
