# Generated by Django 5.0.6 on 2024-07-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='flight_back_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='trip',
            name='flight_out_number',
            field=models.CharField(max_length=40),
        ),
    ]
