# Generated by Django 5.0.6 on 2024-07-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_trip_activities_alter_trip_hotels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='hotels',
        ),
    ]
