# Generated by Django 5.0.6 on 2024-07-08 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_name_alter_trip_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='cities',
        ),
    ]
