# Generated by Django 5.0.6 on 2024-07-08 17:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_remove_trip_cities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='budget',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='flight_back_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='trip',
            name='flight_out_number',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='trip',
            name='flights_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotels_cost',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='itinerary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
