# Generated by Django 5.0.7 on 2024-07-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_alter_trip_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
