# Generated by Django 5.0.6 on 2024-07-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_alter_trip_activities_alter_trip_hotels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='flight_back_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='flight_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
