# Generated by Django 5.0.6 on 2024-07-08 20:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0010_alter_trip_budget_alter_trip_flight_back_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='activities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
        migrations.AlterField(
            model_name='trip',
            name='hotels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), size=None),
        ),
    ]
